import React from 'react';
import Head from 'next/head';
import ProductList from '../components/product/product-list';

export default function Index() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<ProductList />
			</main>
		</>
	);
}
